/**
 * generated by Xtext 2.32.0
 */
package cloudautomation.airflow;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see cloudautomation.airflow.AirflowFactory
 * @model kind="package"
 * @generated
 */
public interface AirflowPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "airflow";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Airflow.cloudautomation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "airflow";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AirflowPackage eINSTANCE = cloudautomation.airflow.impl.AirflowPackageImpl.init();

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.ModelImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Workflows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__WORKFLOWS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.WorkflowImpl <em>Workflow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.WorkflowImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getWorkflow()
   * @generated
   */
  int WORKFLOW = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__TASKS = 2;

  /**
   * The feature id for the '<em><b>Dependencies</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW__DEPENDENCIES = 3;

  /**
   * The number of structural features of the '<em>Workflow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WORKFLOW_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.TaskImpl <em>Task</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.TaskImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getTask()
   * @generated
   */
  int TASK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__NAME = 0;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__DESCRIPTION = 1;

  /**
   * The feature id for the '<em><b>Priority</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__PRIORITY = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK__TYPE = 3;

  /**
   * The number of structural features of the '<em>Task</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.DependencyImpl <em>Dependency</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.DependencyImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getDependency()
   * @generated
   */
  int DEPENDENCY = 3;

  /**
   * The feature id for the '<em><b>Task</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__TASK = 0;

  /**
   * The feature id for the '<em><b>Task Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY__TASK_ID = 1;

  /**
   * The number of structural features of the '<em>Dependency</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEPENDENCY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.PriorityImpl <em>Priority</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.PriorityImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getPriority()
   * @generated
   */
  int PRIORITY = 4;

  /**
   * The feature id for the '<em><b>LOW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIORITY__LOW = 0;

  /**
   * The feature id for the '<em><b>MEDIUM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIORITY__MEDIUM = 1;

  /**
   * The feature id for the '<em><b>HIGH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIORITY__HIGH = 2;

  /**
   * The number of structural features of the '<em>Priority</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIORITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link cloudautomation.airflow.impl.TaskTypeImpl <em>Task Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see cloudautomation.airflow.impl.TaskTypeImpl
   * @see cloudautomation.airflow.impl.AirflowPackageImpl#getTaskType()
   * @generated
   */
  int TASK_TYPE = 5;

  /**
   * The feature id for the '<em><b>SIMPLE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_TYPE__SIMPLE = 0;

  /**
   * The feature id for the '<em><b>COMPOUND</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_TYPE__COMPOUND = 1;

  /**
   * The number of structural features of the '<em>Task Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_TYPE_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see cloudautomation.airflow.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link cloudautomation.airflow.Model#getWorkflows <em>Workflows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Workflows</em>'.
   * @see cloudautomation.airflow.Model#getWorkflows()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Workflows();

  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.Workflow <em>Workflow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Workflow</em>'.
   * @see cloudautomation.airflow.Workflow
   * @generated
   */
  EClass getWorkflow();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Workflow#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cloudautomation.airflow.Workflow#getName()
   * @see #getWorkflow()
   * @generated
   */
  EAttribute getWorkflow_Name();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Workflow#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see cloudautomation.airflow.Workflow#getDescription()
   * @see #getWorkflow()
   * @generated
   */
  EAttribute getWorkflow_Description();

  /**
   * Returns the meta object for the containment reference list '{@link cloudautomation.airflow.Workflow#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see cloudautomation.airflow.Workflow#getTasks()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Tasks();

  /**
   * Returns the meta object for the containment reference list '{@link cloudautomation.airflow.Workflow#getDependencies <em>Dependencies</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dependencies</em>'.
   * @see cloudautomation.airflow.Workflow#getDependencies()
   * @see #getWorkflow()
   * @generated
   */
  EReference getWorkflow_Dependencies();

  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.Task <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task</em>'.
   * @see cloudautomation.airflow.Task
   * @generated
   */
  EClass getTask();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Task#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see cloudautomation.airflow.Task#getName()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Name();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Task#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see cloudautomation.airflow.Task#getDescription()
   * @see #getTask()
   * @generated
   */
  EAttribute getTask_Description();

  /**
   * Returns the meta object for the containment reference '{@link cloudautomation.airflow.Task#getPriority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Priority</em>'.
   * @see cloudautomation.airflow.Task#getPriority()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Priority();

  /**
   * Returns the meta object for the containment reference '{@link cloudautomation.airflow.Task#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see cloudautomation.airflow.Task#getType()
   * @see #getTask()
   * @generated
   */
  EReference getTask_Type();

  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.Dependency <em>Dependency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dependency</em>'.
   * @see cloudautomation.airflow.Dependency
   * @generated
   */
  EClass getDependency();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Dependency#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task</em>'.
   * @see cloudautomation.airflow.Dependency#getTask()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_Task();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Dependency#getTaskId <em>Task Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Task Id</em>'.
   * @see cloudautomation.airflow.Dependency#getTaskId()
   * @see #getDependency()
   * @generated
   */
  EAttribute getDependency_TaskId();

  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.Priority <em>Priority</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Priority</em>'.
   * @see cloudautomation.airflow.Priority
   * @generated
   */
  EClass getPriority();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Priority#getLOW <em>LOW</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>LOW</em>'.
   * @see cloudautomation.airflow.Priority#getLOW()
   * @see #getPriority()
   * @generated
   */
  EAttribute getPriority_LOW();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Priority#getMEDIUM <em>MEDIUM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>MEDIUM</em>'.
   * @see cloudautomation.airflow.Priority#getMEDIUM()
   * @see #getPriority()
   * @generated
   */
  EAttribute getPriority_MEDIUM();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.Priority#getHIGH <em>HIGH</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>HIGH</em>'.
   * @see cloudautomation.airflow.Priority#getHIGH()
   * @see #getPriority()
   * @generated
   */
  EAttribute getPriority_HIGH();

  /**
   * Returns the meta object for class '{@link cloudautomation.airflow.TaskType <em>Task Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task Type</em>'.
   * @see cloudautomation.airflow.TaskType
   * @generated
   */
  EClass getTaskType();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.TaskType#getSIMPLE <em>SIMPLE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>SIMPLE</em>'.
   * @see cloudautomation.airflow.TaskType#getSIMPLE()
   * @see #getTaskType()
   * @generated
   */
  EAttribute getTaskType_SIMPLE();

  /**
   * Returns the meta object for the attribute '{@link cloudautomation.airflow.TaskType#getCOMPOUND <em>COMPOUND</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>COMPOUND</em>'.
   * @see cloudautomation.airflow.TaskType#getCOMPOUND()
   * @see #getTaskType()
   * @generated
   */
  EAttribute getTaskType_COMPOUND();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AirflowFactory getAirflowFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.ModelImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Workflows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__WORKFLOWS = eINSTANCE.getModel_Workflows();

    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.WorkflowImpl <em>Workflow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.WorkflowImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getWorkflow()
     * @generated
     */
    EClass WORKFLOW = eINSTANCE.getWorkflow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKFLOW__NAME = eINSTANCE.getWorkflow_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WORKFLOW__DESCRIPTION = eINSTANCE.getWorkflow_Description();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__TASKS = eINSTANCE.getWorkflow_Tasks();

    /**
     * The meta object literal for the '<em><b>Dependencies</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WORKFLOW__DEPENDENCIES = eINSTANCE.getWorkflow_Dependencies();

    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.TaskImpl <em>Task</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.TaskImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getTask()
     * @generated
     */
    EClass TASK = eINSTANCE.getTask();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__NAME = eINSTANCE.getTask_Name();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK__DESCRIPTION = eINSTANCE.getTask_Description();

    /**
     * The meta object literal for the '<em><b>Priority</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__PRIORITY = eINSTANCE.getTask_Priority();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK__TYPE = eINSTANCE.getTask_Type();

    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.DependencyImpl <em>Dependency</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.DependencyImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getDependency()
     * @generated
     */
    EClass DEPENDENCY = eINSTANCE.getDependency();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__TASK = eINSTANCE.getDependency_Task();

    /**
     * The meta object literal for the '<em><b>Task Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEPENDENCY__TASK_ID = eINSTANCE.getDependency_TaskId();

    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.PriorityImpl <em>Priority</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.PriorityImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getPriority()
     * @generated
     */
    EClass PRIORITY = eINSTANCE.getPriority();

    /**
     * The meta object literal for the '<em><b>LOW</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIORITY__LOW = eINSTANCE.getPriority_LOW();

    /**
     * The meta object literal for the '<em><b>MEDIUM</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIORITY__MEDIUM = eINSTANCE.getPriority_MEDIUM();

    /**
     * The meta object literal for the '<em><b>HIGH</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PRIORITY__HIGH = eINSTANCE.getPriority_HIGH();

    /**
     * The meta object literal for the '{@link cloudautomation.airflow.impl.TaskTypeImpl <em>Task Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see cloudautomation.airflow.impl.TaskTypeImpl
     * @see cloudautomation.airflow.impl.AirflowPackageImpl#getTaskType()
     * @generated
     */
    EClass TASK_TYPE = eINSTANCE.getTaskType();

    /**
     * The meta object literal for the '<em><b>SIMPLE</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_TYPE__SIMPLE = eINSTANCE.getTaskType_SIMPLE();

    /**
     * The meta object literal for the '<em><b>COMPOUND</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TASK_TYPE__COMPOUND = eINSTANCE.getTaskType_COMPOUND();

  }

} //AirflowPackage
