/**
 * generated by Xtext 2.32.0
 */
package cloudautomation.airflow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cloudautomation.airflow.Model#getWorkflows <em>Workflows</em>}</li>
 * </ul>
 *
 * @see cloudautomation.airflow.AirflowPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Workflows</b></em>' containment reference list.
   * The list contents are of type {@link cloudautomation.airflow.Workflow}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Workflows</em>' containment reference list.
   * @see cloudautomation.airflow.AirflowPackage#getModel_Workflows()
   * @model containment="true"
   * @generated
   */
  EList<Workflow> getWorkflows();

} // Model
