/**
 * generated by Xtext 2.32.0
 */
package cloudautomation.airflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Priority</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cloudautomation.airflow.Priority#getLOW <em>LOW</em>}</li>
 *   <li>{@link cloudautomation.airflow.Priority#getMEDIUM <em>MEDIUM</em>}</li>
 *   <li>{@link cloudautomation.airflow.Priority#getHIGH <em>HIGH</em>}</li>
 * </ul>
 *
 * @see cloudautomation.airflow.AirflowPackage#getPriority()
 * @model
 * @generated
 */
public interface Priority extends EObject
{
  /**
   * Returns the value of the '<em><b>LOW</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LOW</em>' attribute.
   * @see #setLOW(String)
   * @see cloudautomation.airflow.AirflowPackage#getPriority_LOW()
   * @model
   * @generated
   */
  String getLOW();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.Priority#getLOW <em>LOW</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LOW</em>' attribute.
   * @see #getLOW()
   * @generated
   */
  void setLOW(String value);

  /**
   * Returns the value of the '<em><b>MEDIUM</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>MEDIUM</em>' attribute.
   * @see #setMEDIUM(String)
   * @see cloudautomation.airflow.AirflowPackage#getPriority_MEDIUM()
   * @model
   * @generated
   */
  String getMEDIUM();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.Priority#getMEDIUM <em>MEDIUM</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>MEDIUM</em>' attribute.
   * @see #getMEDIUM()
   * @generated
   */
  void setMEDIUM(String value);

  /**
   * Returns the value of the '<em><b>HIGH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>HIGH</em>' attribute.
   * @see #setHIGH(String)
   * @see cloudautomation.airflow.AirflowPackage#getPriority_HIGH()
   * @model
   * @generated
   */
  String getHIGH();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.Priority#getHIGH <em>HIGH</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>HIGH</em>' attribute.
   * @see #getHIGH()
   * @generated
   */
  void setHIGH(String value);

} // Priority
