/**
 * generated by Xtext 2.32.0
 */
package cloudautomation.airflow;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cloudautomation.airflow.TaskType#getSIMPLE <em>SIMPLE</em>}</li>
 *   <li>{@link cloudautomation.airflow.TaskType#getCOMPOUND <em>COMPOUND</em>}</li>
 * </ul>
 *
 * @see cloudautomation.airflow.AirflowPackage#getTaskType()
 * @model
 * @generated
 */
public interface TaskType extends EObject
{
  /**
   * Returns the value of the '<em><b>SIMPLE</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SIMPLE</em>' attribute.
   * @see #setSIMPLE(String)
   * @see cloudautomation.airflow.AirflowPackage#getTaskType_SIMPLE()
   * @model
   * @generated
   */
  String getSIMPLE();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.TaskType#getSIMPLE <em>SIMPLE</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SIMPLE</em>' attribute.
   * @see #getSIMPLE()
   * @generated
   */
  void setSIMPLE(String value);

  /**
   * Returns the value of the '<em><b>COMPOUND</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>COMPOUND</em>' attribute.
   * @see #setCOMPOUND(String)
   * @see cloudautomation.airflow.AirflowPackage#getTaskType_COMPOUND()
   * @model
   * @generated
   */
  String getCOMPOUND();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.TaskType#getCOMPOUND <em>COMPOUND</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>COMPOUND</em>' attribute.
   * @see #getCOMPOUND()
   * @generated
   */
  void setCOMPOUND(String value);

} // TaskType
