/**
 * generated by Xtext 2.32.0
 */
package cloudautomation.airflow;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Workflow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link cloudautomation.airflow.Workflow#getName <em>Name</em>}</li>
 *   <li>{@link cloudautomation.airflow.Workflow#getDescription <em>Description</em>}</li>
 *   <li>{@link cloudautomation.airflow.Workflow#getTasks <em>Tasks</em>}</li>
 *   <li>{@link cloudautomation.airflow.Workflow#getDependencies <em>Dependencies</em>}</li>
 * </ul>
 *
 * @see cloudautomation.airflow.AirflowPackage#getWorkflow()
 * @model
 * @generated
 */
public interface Workflow extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see cloudautomation.airflow.AirflowPackage#getWorkflow_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.Workflow#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see cloudautomation.airflow.AirflowPackage#getWorkflow_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link cloudautomation.airflow.Workflow#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link cloudautomation.airflow.Task}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see cloudautomation.airflow.AirflowPackage#getWorkflow_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<Task> getTasks();

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link cloudautomation.airflow.Dependency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see cloudautomation.airflow.AirflowPackage#getWorkflow_Dependencies()
   * @model containment="true"
   * @generated
   */
  EList<Dependency> getDependencies();

} // Workflow
