/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link AirflowWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractAirflowWebModule extends DefaultWebModule {

}
