/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAirflowScopeProvider extends DelegatingScopeProvider {
}
