/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.parser.antlr;

import cloudautomation.parser.antlr.internal.InternalAirflowParser;
import cloudautomation.services.AirflowGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AirflowParser extends AbstractAntlrParser {

	@Inject
	private AirflowGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAirflowParser createParser(XtextTokenStream stream) {
		return new InternalAirflowParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AirflowGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AirflowGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
