/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AirflowAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("cloudautomation/parser/antlr/internal/InternalAirflow.tokens");
	}
}
