/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class AirflowWebModule extends AbstractAirflowWebModule {
}
