/*
 * generated by Xtext 2.32.0
 */
package cloudautomation.web;

import cloudautomation.AirflowRuntimeModule;
import cloudautomation.AirflowStandaloneSetup;
import cloudautomation.ide.AirflowIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class AirflowWebSetup extends AirflowStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AirflowRuntimeModule(), new AirflowIdeModule(), new AirflowWebModule()));
	}
	
}
