/*
 * generated by Xtext 2.32.0
 */
package cloudautomation;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class AirflowStandaloneSetup extends AirflowStandaloneSetupGenerated {

	public static void doSetup() {
		new AirflowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
